### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by JoeyDarbyshire** [TiiaAurora/LS-public-issue-tracker#62] opened 2023-03-15 14:02 UTC
After the update to change the class name from "Painter" to "Artist", I am receiving a TypeError in the console now.  This is showing up in both Chrome and Firefox. 

This type error is causing characters to not display in either the Overview or Roster Matrix.   The "Add Character" button is not working either.

![image](https://user-images.githubusercontent.com/20380456/225332264-39d7c5f8-102c-4237-81d4-9f4eee708643.png)
![image](https://user-images.githubusercontent.com/20380456/225332364-8cb300f1-1148-418f-8cf7-15345ec827f4.png)

Errors:
```
Uncaught (in promise) TypeError: p[a.cls] is undefined
    update https://leapstone.netlify.app/_app/chunks/ClassDisplay-48cca087.js:1
    Oe https://leapstone.netlify.app/_app/chunks/index-958e3c2f.js:4
    C https://leapstone.netlify.app/_app/chunks/ClassDisplay-48cca087.js:1
    Oa https://leapstone.netlify.app/_app/pages/index.svelte-bec3cff9.js:37
    nu https://leapstone.netlify.app/_app/pages/index.svelte-bec3cff9.js:37
    au https://leapstone.netlify.app/_app/pages/index.svelte-bec3cff9.js:37
    Oe https://leapstone.netlify.app/_app/chunks/index-958e3c2f.js:4
    cu https://leapstone.netlify.app/_app/pages/index.svelte-bec3cff9.js:37
    Zu https://leapstone.netlify.app/_app/pages/index.svelte-bec3cff9.js:49
    Ya https://leapstone.netlify.app/_app/pages/index.svelte-bec3cff9.js:49
    Ju https://leapstone.netlify.app/_app/pages/index.svelte-bec3cff9.js:49
    Oe https://leapstone.netlify.app/_app/chunks/index-958e3c2f.js:4
    oh https://leapstone.netlify.app/_app/pages/index.svelte-bec3cff9.js:49
    bt https://leapstone.netlify.app/_app/start-7680b9f0.js:1
    Rt https://leapstone.netlify.app/_app/start-7680b9f0.js:1
    Jt https://leapstone.netlify.app/_app/chunks/index-958e3c2f.js:1
    uh https://leapstone.netlify.app/_app/pages/__layout.svelte-e8d572a8.js:43
    Oe https://leapstone.netlify.app/_app/chunks/index-958e3c2f.js:4
    bh https://leapstone.netlify.app/_app/pages/__layout.svelte-e8d572a8.js:45
    wt https://leapstone.netlify.app/_app/start-7680b9f0.js:1
    Lt https://leapstone.netlify.app/_app/start-7680b9f0.js:1
    Oe https://leapstone.netlify.app/_app/chunks/index-958e3c2f.js:4
    At https://leapstone.netlify.app/_app/start-7680b9f0.js:1
    Ne https://leapstone.netlify.app/_app/start-7680b9f0.js:1
    _hydrate https://leapstone.netlify.app/_app/start-7680b9f0.js:1
```
```
Uncaught (in promise) TypeError: t is undefined
    _e https://leapstone.netlify.app/_app/chunks/index-958e3c2f.js:1
    p https://leapstone.netlify.app/_app/pages/__layout.svelte-e8d572a8.js:31
    Rt https://leapstone.netlify.app/_app/chunks/index-958e3c2f.js:4
    ft https://leapstone.netlify.app/_app/chunks/index-958e3c2f.js:4
    promise callback*at https://leapstone.netlify.app/_app/chunks/index-958e3c2f.js:4
    Ft https://leapstone.netlify.app/_app/chunks/index-958e3c2f.js:4
    ctx https://leapstone.netlify.app/_app/chunks/index-958e3c2f.js:4
    J2 https://leapstone.netlify.app/_app/pages/__layout.svelte-e8d572a8.js:31
    f https://leapstone.netlify.app/_app/chunks/index-bc57e10b.js:1
    Wt https://leapstone.netlify.app/_app/chunks/store-c0c95aee.js:1

```

**Comment by TiiaAurora** [comment] 2023-03-15 21:00
Does Ctrl + f5 help?

**Comment by JoeyDarbyshire** [comment] 2023-03-15 21:19
No, I even tried disabling the cache in console.

**Comment by nwk6661** [comment] 2023-03-15 21:49
So it seems the problem is caused after first clicking the "new character" button from a working roster. The new character entry has class name "unset", which isn't found in the array of all class names and thus causes an issue when trying to get the name property from that object.

**Temporary fix**
1. open dev console (f12)
2. go to application tab
3. click on "local storage" on the left, then the leapstone entry under that
4. double click the value for the key "data", copy the selection to clipboard
5. paste that json into text editor of choice
6. remove all "new character" json objects from the characters array
7. (optional) if necessary, re-minify the json via a site like https://www.cleancss.com/json-minify/
8. back in the dev console, double click the value for the "data" entry again and paste in your modified json
9. refresh

This at least restores functionality for your existing characters. Do **not** try to create a new character, it will break again.

If you were trying to create an artist, keep one of the "new character" entries in the json and change the class name property from unset to "painter". follow the rest of the steps to set the value of the local data with the new json. You will now have a new artist character as if you clicked the button and selected artist

**Comment by coldino** [comment] 2023-03-15 23:48
Blame the Artist :(

Should be fixed in a few minutes.

**Comment by coldino** [comment] 2023-03-16 00:02
So this was exactly as @nwk6661 suggested. Thanks for helping out.

The need to rename from Painter to Artist without breaking any characters already created meant we needed a new mechanism to translate internal IDs into display names. All was good except that the `unset` class we use for new character was forgotten.  Whoops!

Still, the fix should be live now.

**Closed by coldino** 2023-03-16 00:02 UTC
