### ISSUE TITLE
Every daily reset my first character name is being changed

### ISSUE THREAD

**Issue by mrowkaadrian** [TiiaAurora/LS-public-issue-tracker#32] opened 2022-05-02 11:55 UTC
Every time it moves to the next day I have my main character renamed to the same name as last character I left selected previous day. Leaving the screenshot if my description wasn't too easy to understand the issue:
![bug](https://user-images.githubusercontent.com/34339501/166229776-8d5dc5aa-141d-475e-b4e5-99ceab0b1a16.png)

Edit: I'm using Firefox 99.0.1

**Comment by coldino** [comment] 2022-05-02 12:03
Interesting - we don't see this. Can I ask which browser you are using?

**Comment by xTavi** [comment] 2022-05-02 15:04
It happened to me too, the main char name is getting changed from time to time, I tried to reproduce but I can't. I will keep you updated

**Comment by coldino** [comment] 2022-05-02 21:39
Thanks.

Spent some more time on this. Still unable to reproduce locally and also quite confused it affects name but not the tier, as shown in the screenshot. Very much interesting in any new information. Which browser? Does the page feel "slow" to react on that PC?

In the mean time I'll add some extra protection around the weekly reset code in an effort to bypass this issue, even though it isn't clear what it actually is.

**Comment by xuerion** [comment] 2022-05-03 00:39
I have the same issue daily and noticed the same pattern as described by OP.

> I have my main character renamed to the same name as last character I left selected previous day.

I am on latest Firefox 99.0.1, though it started happening even before upgrading to 99 but could be a Firefox thing 🤷 The local storage data is actually changed so not a display issue. Not sure what is writing to local storage but it only happens after daily reset since closing and reopening doesn't recreate, only reopening the next day. Let me know if you need any more info.

**Comment by coldino** [comment] 2022-05-03 08:15
Question... Do any of you have the site open in multiple tabs? I would recommend only having one tab open with any site that stores its data in local storage.

We do try to sync up when another tab changes the data, but we rely on a slowish notification mechanism built into the browser for that.

**Comment by xuerion** [comment] 2022-05-03 08:42
I do not, my usage is purely on one tab, and so this bug only happens on browser restart. The above multiple tabs was just trying to narrow down the root cause - bug happens on new tab creation, so initial load I guess, I wasn't having two tabs open and editing one then checking the other.

**Comment by mrowkaadrian** [comment] 2022-05-04 08:11
Sorry for not responding. It looks like that happens every time my browser start as @xuerion mentioned. Added my browser to the description of the issue (that's firefox 99.0.1)

**Comment by coldino** [comment] 2022-05-04 10:48
Thanks for the extra info. Knowing this happens on browser restart gives another avenue of investigation.

**Comment by coldino** [comment] 2022-05-06 18:47
With all the structural changes recently I'd love to hear from anyone who sees this after today.

**Comment by LittleBigDev** [comment] 2022-05-06 19:23
Just got the renaming bug today at 6pm (Paris time)

**Comment by LittleBigDev** [comment] 2022-05-08 08:36
Same thing this morning, BEFORE the reset. I closed my browser (and shut off the pc) around 1am (french time) and just came back. Opened the browser : first character was renamed (reset is in 1.5h)

**Comment by LittleBigDev** [comment] 2022-05-08 11:24
I left browser + tab on leapstone.netlify.app open : no renaming bug. Does not look like it's about daily reset, more about browser close + reopen with all saved tabs session.

**Comment by coldino** [comment] 2022-05-08 15:36
Okay, thanks, this extra info has allowed us to reproduce the issue reliably. It is restricted to Firefox but occurs on all browser restarts (not just end of week).

The fact that it is Firefox only makes it kind of mind boggling, but it also gives an easy temporary workaround for anyone suffering from it - try another browser. We tested on Chrome, Edge and Opera without running into the issue.

We still have to find the issue itself, but this is a big step - thanks everyone for the reports.

**Comment by TiiaAurora** [comment] 2022-05-09 13:40
We did a test version that might fix the bug. Can you export your data from leapstone (link in the footer) import it on the test site and play around with it and try to trigger it to bug out again? https://62791425b31f630009449a2e--leapstone.netlify.app/

**Comment by LittleBigDev** [comment] 2022-05-09 17:24
Will do tonight

**Comment by LittleBigDev** [comment] 2022-05-09 18:05
Ok I tested on official site : bug reproduced on every tries.
Tested on test site : impossible to reproduce.

Well done.

**Comment by LittleBigDev** [comment] 2022-05-09 18:07
BTW, a simple workaround : close the tab, THEN close firefox.

When you come back you have to reopen a tab for the app, but at least, no renaming issue.

**Comment by coldino** [comment] 2022-05-09 18:56
Pushed this live. Let us know if this bug pops up its ugly head again!

**Closed by coldino** 2022-05-09 18:56 UTC
Labels: bug

**Comment by LittleBigDev** [comment] 2022-05-09 21:44
Yup, seems like it's fixed. I can't make it bug anymore.

Well done !

**Comment by LittleBigDev** [comment] 2022-05-15 12:53
DAMN I just had the bug again!

This time I had the app tab opened in a firefox windows + another firefox windows (with a paused youtube video).  
The daily reset happened like this (my Windows session was locked)
